# Generated by Django 5.0.3 on 2024-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_order_order_type_alter_trade_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.01, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='exchange_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='additional_services',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='commission_type',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='competitiveness',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='exchange_currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='regulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.015, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('exchange', 'Обмен')], max_length=8),
        ),
    ]
