# Generated by Django 5.0.3 on 2024-05-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=10, unique=True)),
                ('currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
